### PR TITLE
Support XPath attribute-existence search for empty-valued HTML element attributes

### LINKED ISSUE #1: HTML elements with empty attribute values not found during XPath attribute-existence search
Hi @willforde - this library looks neat!  I'm experimenting with it as an alternative to some `lxml` and `html5lib` based parsing.

One quirk I noticed is that HTML elements with empty attribute values (like the 'checked' property in `<input type="checkbox" checked>` aren't found when searching using XPath attribute-presence tests (such as `.//input[@checked]`).

It looks like that's because [Python's `ElementPath` empty-attribute-search implementation](https://github.com/python/cpython/blob/c9ed0327a9c741a1808926b409df29467baf303a/Lib/xml/etree/ElementPath.py#L249-L254) requires not only attribute name (key) presence but also the presence of a non-`None` value.

While figuring that out, I noticed that there might be a straightforward way to address that within `htmlement`; I'll follow up on this issue with a pull request in a few moments.

### PR DESCRIPTION
**Pull request by jayaddison**
Resolves #1.

### CODE REVIEW

**Comment by jayaddison** [comment]
Small ping about this @willforde - if there's any chance it'll make it into `htmlement`, then that'd be a great way for me to unlock a ton more work I have lined up for myself.

**Comment by willforde** [comment]
Sorry for the delay. Will look at this now.

**Comment by willforde** [comment]
Wow. Very nice simple fix. Thank you so much. I will push an update to PYPI later.

**Comment by jayaddison** [comment]
No worries - thank you!

**Pull request merged**
